const mockApiMeals = {
  meals: [
    {
      idMeal: '52929',
      strMeal: 'Timbits',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strInstructions: 'cook',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
      strTags: 'Snack,Treat',
      strYoutube: 'https://www.youtube.com/watch?v=fFLn1h80AGQ',
      strIngredient1: 'Flour',
      strIngredient2: 'Sugar',
      strIngredient3: 'Baking Powder',
      strIngredient4: 'Salt',
      strIngredient5: 'Egg',
      strIngredient6: 'Milk',
      strIngredient7: 'Oil',
      strIngredient8: 'Oil',
      strIngredient9: 'Icing Sugar',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 cups ',
      strMeasure2: '1/3 cup',
      strMeasure3: '3 tsp',
      strMeasure4: '½ tsp',
      strMeasure5: '1 beaten',
      strMeasure6: '¾ cup',
      strMeasure7: '3 tbs',
      strMeasure8: 'for frying',
      strMeasure9: 'garnish',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/drop-doughnuts-133877',
      dateModified: null,
    },
    {
      idMeal: '53013',
      strMeal: 'Big Mac',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'American',
      strInstructions: 'cook',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=C5J39YnnPsg',
      strIngredient1: 'Minced Beef',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Sesame Seed Burger Buns',
      strIngredient4: 'Onion',
      strIngredient5: 'Iceberg Lettuce',
      strIngredient6: 'Cheese',
      strIngredient7: 'Dill Pickles',
      strIngredient8: 'Mayonnaise',
      strIngredient9: 'White Wine Vinegar',
      strIngredient10: 'Pepper',
      strIngredient11: 'Mustard',
      strIngredient12: 'Onion Salt',
      strIngredient13: 'Garlic Powder',
      strIngredient14: 'Paprika',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '400g',
      strMeasure2: '2 tbs',
      strMeasure3: '2',
      strMeasure4: 'Chopped',
      strMeasure5: '1/4 ',
      strMeasure6: '2 sliced',
      strMeasure7: '2 large',
      strMeasure8: '1 cup ',
      strMeasure9: '2 tsp',
      strMeasure10: 'Pinch',
      strMeasure11: '2 tsp',
      strMeasure12: '1 1/2 tsp ',
      strMeasure13: '1 1/2 tsp ',
      strMeasure14: '1/2 tsp',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.delicious.com.au/recipes/finally-recipe-worlds-top-selling-burger-big-mac/5221ee4a-279e-4a0b-8629-f442dc46822e',
      dateModified: null,
    },
    {
      idMeal: '52774',
      strMeal: 'Pad See Ew',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Thai',
      strInstructions: 'cook',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      strTags: 'Pasta',
      strYoutube: 'https://www.youtube.com/watch?v=Ohy1DELF4is',
      strIngredient1: 'rice stick noodles',
      strIngredient2: 'dark soy sauce',
      strIngredient3: 'oyster sauce',
      strIngredient4: 'soy sauce',
      strIngredient5: 'white vinegar',
      strIngredient6: 'sugar',
      strIngredient7: 'water',
      strIngredient8: 'peanut oil',
      strIngredient9: 'garlic',
      strIngredient10: 'Chicken',
      strIngredient11: 'Egg',
      strIngredient12: 'Chinese broccoli',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '6oz/180g',
      strMeasure2: '2 tbsp',
      strMeasure3: '2 tbsp',
      strMeasure4: '2 tsp',
      strMeasure5: '2 tsp',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tbsp',
      strMeasure8: '2 tbsp',
      strMeasure9: '2 cloves',
      strMeasure10: '1 cup',
      strMeasure11: '1',
      strMeasure12: '4 cups',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      dateModified: null,
    },
    {
      strMeal: 'Mbuzi Choma (Roasted Goat)',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/cuio7s1555492979.jpg',
      idMeal: '52968',
    },
    {
      strMeal: 'Bread omelette',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg',
      idMeal: '53076',
    },
  ],
};

export default mockApiMeals;
